import { OpenRouter } from '@openrouter/sdk';

function getClient() {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    throw new Error('Missing configuration: OPENROUTER_API_KEY required');
  }
  return new OpenRouter({ apiKey });
}

const MODEL = 'google/gemini-2.5-flash-image';

function extractImage(message) {
  let imageBuffer = null;
  let mimeType = 'image/png';
  let text = message.content || '';

  if (message.images && message.images.length > 0) {
    const dataUrl = message.images[0].imageUrl?.url;
    if (dataUrl) {
      const match = dataUrl.match(/^data:(image\/\w+);base64,(.+)$/);
      if (match) {
        mimeType = match[1];
        imageBuffer = Buffer.from(match[2], 'base64');
      }
    }
  }

  if (!imageBuffer) {
    throw new Error('No image generated by Gemini API via OpenRouter');
  }

  return { imageBuffer, mimeType, text };
}

// Generate image using Gemini 3.1 Flash Image via OpenRouter SDK (Nano Banana)
export async function generateBananaImage(prompt, options = {}) {
  const openrouter = getClient();

  const result = await openrouter.chat.send({
    chatGenerationParams: {
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      modalities: ['image', 'text'],
    },
  });

  const message = result.choices?.[0]?.message;
  if (!message) {
    throw new Error('No content returned from OpenRouter API');
  }

  return extractImage(message);
}

// Edit/transform an existing image using Gemini via OpenRouter SDK
export async function editBananaImage(imageBuffer, prompt, options = {}) {
  const openrouter = getClient();

  const base64 = imageBuffer.toString('base64');
  const inputMime = options.mimeType || 'image/png';
  const dataUrl = `data:${inputMime};base64,${base64}`;

  const result = await openrouter.chat.send({
    chatGenerationParams: {
      model: MODEL,
      messages: [{
        role: 'user',
        content: [
          { type: 'image_url', image_url: { url: dataUrl } },
          { type: 'text', text: prompt },
        ],
      }],
      modalities: ['image', 'text'],
    },
  });

  const message = result.choices?.[0]?.message;
  if (!message) {
    throw new Error('No content returned from OpenRouter API');
  }

  return extractImage(message);
}
