import { GoogleGenAI } from '@google/genai';

// Generate image using Google Gemini 2.5 Flash Image model (Nano Banana)
export async function generateBananaImage(prompt, options = {}) {
  const { GEMINI_API_KEY } = process.env;

  if (!GEMINI_API_KEY) {
    throw new Error('Missing Gemini configuration: GEMINI_API_KEY required');
  }

  const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

  let response;
  try {
    response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: prompt,
      config: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    });
  } catch (apiErr) {
    const err = new Error(parseGeminiError(apiErr));
    err.statusCode = apiErr.status || 502;
    throw err;
  }

  if (!response.candidates || !response.candidates[0]?.content?.parts) {
    throw new Error('No content returned from Gemini API');
  }

  let imageBuffer = null;
  let mimeType = 'image/png';
  let text = '';

  for (const part of response.candidates[0].content.parts) {
    if (part.text) {
      text += part.text;
    } else if (part.inlineData) {
      imageBuffer = Buffer.from(part.inlineData.data, 'base64');
      mimeType = part.inlineData.mimeType || 'image/png';
    }
  }

  if (!imageBuffer) {
    throw new Error('No image generated by Gemini API');
  }

  return { imageBuffer, mimeType, text };
}

function parseGeminiError(err) {
  // Extract clean message from Gemini SDK error
  if (err.message) {
    try {
      const parsed = JSON.parse(err.message);
      return parsed?.error?.message || err.message;
    } catch {
      return err.message;
    }
  }
  return 'Unknown Gemini API error';
}
